service: wuolah-test-backend
frameworkVersion: '3'

custom:
  users:
    tableName: users
  contests:
    tableName: contests

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-3
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
            - Fn::GetAtt: [ContestsTable, Arn]
  environment:
    USERS_TABLE: ${self:custom.users.tableName}

functions:
  api:
    handler: src/app.handler
    events:
      - httpApi: '*'

resources:
  - ${file(resources/dynamodb.yml)}
