Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: hash
          AttributeType: S
        - AttributeName: name
          AttributeType: S
        - AttributeName: tickets
          AttributeType: N
        - AttributeName: lastIssuedTicket
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.users.tableName}
  ContestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: contestId
          AttributeType: S
      KeySchema:
        - AttributeName: contestId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.contests.tableName}